"""second

Revision ID: 34c4198b15f3
Revises: a12e728b7243
Create Date: 2022-12-21 23:56:43.396575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c4198b15f3'
down_revision = 'a12e728b7243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
