"""first

Revision ID: a12e728b7243
Revises: 
Create Date: 2022-12-21 23:51:28.475849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12e728b7243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distortion_record', sa.Column('record_id', sa.Integer(), nullable=False))
    op.drop_index('ix_distortion_record_user_id', table_name='distortion_record')
    op.create_index(op.f('ix_distortion_record_record_id'), 'distortion_record', ['record_id'], unique=True)
    op.drop_constraint('distortion_record_user_id_fkey', 'distortion_record', type_='foreignkey')
    op.create_foreign_key(None, 'distortion_record', 'record', ['record_id'], ['id'])
    op.drop_column('distortion_record', 'user_id')
    op.add_column('emotion_record', sa.Column('record_id', sa.Integer(), nullable=False))
    op.drop_index('ix_emotion_record_user_id', table_name='emotion_record')
    op.create_index(op.f('ix_emotion_record_record_id'), 'emotion_record', ['record_id'], unique=True)
    op.drop_constraint('emotion_record_user_id_fkey', 'emotion_record', type_='foreignkey')
    op.create_foreign_key(None, 'emotion_record', 'record', ['record_id'], ['id'])
    op.drop_column('emotion_record', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion_record', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emotion_record', type_='foreignkey')
    op.create_foreign_key('emotion_record_user_id_fkey', 'emotion_record', 'record', ['user_id'], ['id'])
    op.drop_index(op.f('ix_emotion_record_record_id'), table_name='emotion_record')
    op.create_index('ix_emotion_record_user_id', 'emotion_record', ['user_id'], unique=False)
    op.drop_column('emotion_record', 'record_id')
    op.add_column('distortion_record', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'distortion_record', type_='foreignkey')
    op.create_foreign_key('distortion_record_user_id_fkey', 'distortion_record', 'record', ['user_id'], ['id'])
    op.drop_index(op.f('ix_distortion_record_record_id'), table_name='distortion_record')
    op.create_index('ix_distortion_record_user_id', 'distortion_record', ['user_id'], unique=False)
    op.drop_column('distortion_record', 'record_id')
    # ### end Alembic commands ###
